### PR TITLE
Declutter Internal Shape of Vector

### PR DESCRIPTION
**Pull request by emwap**
As a step on the way to implementing #91, this pull request declutters the internal representation of `Pull`.
`Pull DIM0 a` is represented as a scalar `Internal a`.
`Pull DIM1 a` is represented as a list `[Internal a]`.

With this change there should be no need for the `Feldspar.SimpleVector` module.

However, it breaks some of the assumptions in the `ExternalProgram` module in feldspar-compiler.

/cc @emilaxelsson, @josefs, @pjonsson

### CODE REVIEW

**Comment by pjonsson** [comment]
Doesn't the other vector types (Push, Manifest, etc) need the same kind of patch?

The new type family should morally be closed. What advantage does the closed type family bring if we have to have the open type family around anyways?

ExternalProgram is meant as a tool for debugging and testing the compiler so assume that there is an expert user for that. I assume we need some special hardwired knowledge in there to recognise DIM0/DIM1 arrays.

**Comment by emwap** [comment]
Yes, I will add instances for `Push` and `Manifest`.

The only "advantage" is compatibility with older GHC (pre 7.8) versions. With 7.10 coming out soon, I guess we could remove this.

Would you be ok with putting `ExternalProgram` behind a cabal-flag (default false) and temporarily breaking it?

**Comment by pjonsson** [comment]
My question was actually the other way around: if open type families are enough to get the functionality we want, why add extra code for closed type families? Haskell support on RHEL seems to have stopped updating around 7.6 so I'm a bit split about deprecating that right now. 

Add the cabal flag for now and I'll patch ExternalProgram at a later date. Since this is still hot in your cache: can you please summarise the data structure layout changes from this patch so I don't have to reverse-engineer that when I get to updating ExternalProgram.

**Comment by emwap** [comment]
The motivation for the closed family is as you said before, it's morally closed and I wanted to express that to GHC. I guess we could consider any drawbacks of leaving it open.

`Pull DIM0 a` is represented as `Internal a`.
`Pull DIM1 a` is represented as `[Internal a]`.
`Pull DIM2 a` is represented as `([Length], [Internal a])`.

Only the `DIM0` and `DIM1` cases have changed and the representation for `DIM2` and above is the same as before.

**Comment by pjonsson** [comment]
ExternalProgram might actually work as is with that representation.

**Comment by emwap** [comment]
It does, see branch Feldspar/feldspar-compiler#197

**Comment by pjonsson** [comment]
Ok, so can this be merged now?

**Comment by emwap** [comment]
Yes, but that will break test-cases in Feldspar/feldspar-compiler. I still have some quirks to sort out there.

**Comment by josefs** [comment]
A suggestion wrt to Manifest: the easiest way to deal with Manifest is probably to define it as follows:

~~~
data Manifest sh a = Syntax a => Manifest (InternalShape sh a)
~~~

**Pull request merged**
